print("my first code")
print("my second code")
print("my third code")
print("my fourth code")
print("my fifth code")
print("my sixth code")
print("my seventh code")
print("my eighth code")
print("my ninth code")
print("my tenth code")
print("my eleventh code")
print("my twelfth code")
print("my thirteenth code")


